# TITLE:  Weekend Rewards
# Ver:    1.0
# AUTHOR: CyberGoose

days:
  sunday: true
  monday: false
  tuesday: false
  wednesday: false
  thursday: false
  friday: false
  saturday: true

multiplier: 2