# TITLE:  Weekend Rewards
# Ver:    1.2.0
# AUTHOR: CyberGoose

# Set the days you want to give more experience to true

# Set the multiplier to a integer to multiply the experience dropped
#                           (ex: coal drops 2xp.. coal now drops 4xp)

# Set drops.blocks or drops.entities to true to allow xp multiplier and special
#   drops to affect block break or entity kills
days:
  sunday: true
  monday: false
  tuesday: false
  wednesday: false
  thursday: false
  friday: false
  saturday: true

multiplier: 2.0

drops:
  blocks: true
  entities: true
  cooking: true
  breeding: true